name: 'Pinata: Build and Deploy'
on:
  workflow_dispatch: null
  push:
    branches:
      - main
jobs:
  build:
    name: Build NUXT
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn generate

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: nuxt-public-dist
          path: dist
  deploy:
    name: Deploy to IPFS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: nuxt-public-dist
          path: dist
      - name: Deploy to Pinata
        uses: aquiladev/ipfs-action@v0.1.5
        id: pinata
        with:
          path: dist
          service: pinata
          pinataKey: '${{ secrets.PINATA_KEY }}'
          pinataSecret: '${{ secrets.PINATA_SECRET }}'
          pinataPinName: harper.eth
